spring:
  application:
    name: forum-service
  datasource:
    url: jdbc:postgresql://forum-service-forum-rtnzrfr.h.aivencloud.com:13271/defaultdb?sslmode=require
    username: avnadmin
    password: ${AIVEN_PASS}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  data:
    mongodb:
      uri: ${MONGO_URI}